### ISSUE TITLE
cname probe not work

### ISSUE THREAD

**Issue by iflody** [projectdiscovery/httpx#239] opened 2021-04-17 02:49 UTC
In pr #108 seems that cname probe has been added, but when I try it locally it seems that not work,

Use the test case in the original pr:

```
https://www.hackerone.com
https://api.hackerone.com
https://mta-sts.hackerone.com
https://mta-sts.managed.hackerone.com
https://support.hackerone.com
https://mta-sts.forwarding.hackerone.com
https://docs.hackerone.com
https://resources.hackerone.com
```

```
./httpx -l domains.txt -cname

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.0.5

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
https://mta-sts.forwarding.hackerone.com
http://mta-sts.managed.hackerone.com
http://mta-sts.hackerone.com
http://api.hackerone.com
http://docs.hackerone.com
http://www.hackerone.com
http://resources.hackerone.com
http://support.hackerone.com
```

When I dig into source code I find that in [internal/runner/runner.go](https://github.com/projectdiscovery/httpx/blob/dc893166106c78fa0bfba0ba13ea9ba3b7f080a1/internal/runner/runner.go#L705):

```golang
dnsData, err := hp.Dialer.GetDNSData(domain)
```

and in fast dialer [GetDNSData function](https://github.com/projectdiscovery/fastdialer/blob/6cf6d0fd6e3a3e30bbe9dacbf7506f5cc578ad51/fastdialer/dialer.go#L137):

```golang
		data, err = d.dnsclient.Resolve(hostname)
		if err != nil && d.options.EnableFallback {
			data, err = d.dnsclient.ResolveWithSyscall(hostname)
		}
		if err != nil {
			return nil, err
		}
		if data == nil {
			return nil, errors.New("could not resolve host")
		}
		b, _ := data.Marshal()
		err = d.hm.Set(hostname, b)
		if err != nil {
			return nil, err
		}
		return data, nil
```

It call [retryabledns's Resolve function](https://github.com/projectdiscovery/retryabledns/blob/d61798f8cbe3281b78ad7a693152f41dab710cf1/client.go#L53) which only query for the A record:

```golang
func (c *Client) Resolve(host string) (*DNSData, error) {
	return c.Query(host, dns.TypeA)
}
```

So I think it is the root cause? I think the fastdialer need to add an function for A|CNAME type record.

**Comment by iflody** [comment] 2021-04-17 03:13
I have make a pr projectdiscovery/fastdialer#11 , it is ugly but seems will work

**Comment by ehsandeep** [comment] 2021-04-17 08:05
```sh
test $cat h1.txt 

https://www.hackerone.com
https://api.hackerone.com
https://mta-sts.hackerone.com
https://mta-sts.managed.hackerone.com
https://support.hackerone.com
https://mta-sts.forwarding.hackerone.com
https://docs.hackerone.com
https://resources.hackerone.com

test $cat h1.txt | httpx -silent -cname
https://docs.hackerone.com [hacker0x01.github.io]
https://mta-sts.managed.hackerone.com [hacker0x01.github.io]
https://mta-sts.hackerone.com [hacker0x01.github.io]
https://api.hackerone.com
https://support.hackerone.com [hackerone.zendesk.com]
https://resources.hackerone.com [read.uberflip.com]
https://www.hackerone.com
https://mta-sts.forwarding.hackerone.com [hacker0x01.github.io]
```

@iflody this works for me, I'm unable to reproduce this, on what system you running this, as per banner you are on the latest version of httpx.

**Comment by iflody** [comment] 2021-04-17 09:25
Thanks for your reply, I try to clear my dns cache locally, and it just works, I can't repeat this bug again, sorry.

**Comment by ehsandeep** [comment] 2021-04-17 09:48
Np @iflody, thanks for confirming this, can we close this issue now and related PR?

**Comment by iflody** [comment] 2021-04-17 09:53
Yes, I will do it.

**Comment by nvdadt** [comment] 2021-06-15 03:29
-cname - does not work in latest build . Any work around for this ?

**Comment by nvdadt** [comment] 2021-06-17 04:03
Thanks for the quick fix. From where do I get this latest build ?

**Comment by ehsandeep** [comment] 2021-06-18 06:28
@nvdadt fix is merged into `dev` branch, you can pull dev branch with `GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx@dev` before we create a new build.

**Comment by nvdadt** [comment] 2021-06-23 05:36
Thanks @ehsandeep this worked. Please let me know when this goes to new build.

**Closed** 2021-06-24 08:35 UTC
Labels: Status: Completed, Type: Bug

**Comment by ehsandeep** [comment] 2021-06-24 08:37
@nvdadt this is now fixed in the latest release.
