### ISSUE TITLE
The random agent selection do not work as expected

### ISSUE THREAD

**Issue by andrei-the-developer** [projectdiscovery/httpx#1089] opened 2023-04-15 10:23 UTC
### Steps To Reproduce:  
1) run in terminal httpx -u 127.0.0.1
2) tail /var/log/apache2/access.log
3) The last row if the file should be the httpx request, and in the agent field you see all of the browsers instead of only one

**Comment by bugrakocabay** [comment] 2023-06-11 09:51
This looks like a valid user-agent value. httpx uses [this](https://github.com/corpix/uarand) this package to generate a random user-agent.

The user-agent string you provided contains references to multiple browsers because it is a common practice for some browsers to include information about other browsers in their user-agent strings. This is often done for compatibility or rendering purposes.

**Comment by ehsandeep** [comment] 2023-06-11 21:23
@andrei-the-developer This is not specific to httpx but more of a result of the underlying library used for random user-agent and valid in format.

Closing this issue since this is not a bug, but FYI, we will be replacing the underlying library with https://github.com/projectdiscovery/useragent for a better selection of the latest user agents and getting tracked at https://github.com/projectdiscovery/httpx/issues/649

**Closed by ehsandeep** 2023-06-11 21:23 UTC
Labels: Type: Bug
