### ISSUE TITLE
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by kiroxan** [projectdiscovery/httpx#210] opened 2021-03-06 20:45 UTC
Hello,

some urls fails to be resolved with httpx with a timeout issue while the hosts are working fine

echo "jigsaw.w3.org" | docker run --rm -i httpx -debug

[DBG] Failure 'http://jigsaw.w3.org': GET http://jigsaw.w3.org giving up after 1 attempts: Get "http://jigsaw.w3.org": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

can you help me resolve this ? i tried incresing timeout and retries but no success.

thank you

**Comment by celsec** [comment] 2021-03-10 17:49
Your computer is closing the connection due to the server taking too much time to respond. The issue is most likely not on httpx since this error message comes from the net/http golang package.

**Comment by ehsandeep** [comment] 2021-03-12 14:43
@kiroxan looks like this is an issue with your local system and not `httpx`, which works fine with docker.

```
echo jigsaw.w3.org | docker run -i projectdiscovery/httpx:latest -silent
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
https://jigsaw.w3.org
```

**Closed by ehsandeep** 2021-03-12 14:43 UTC
