### ISSUE TITLE
Screenshot function ignores additional HTTP headers

### ISSUE THREAD

**Issue by xYantix** [projectdiscovery/httpx#1237] opened 2023-06-17 03:55 UTC
### httpx version:
[INF] Current httpx version v1.3.2 (latest)

### Current Behavior:
When using the -ss flag httpx sends 2 requests to the target address. I believe the first is used to log the request and the second is used to actually take the screenshot. 
When you specify additional HTTP headers to be included in your request (eg. a Host header), it is included in the first request but not the second, which affects the output.

### Expected Behavior:
Ideally, both requests should be the same so that the screenshot is a true representation of what has been requested from the CLI.

### Steps To Reproduce:
1. Fire up Burp or your favourite interception proxy tool so that which requests are actually sent by httpx.
2. Run httpx -u 156.55.139.166 -H "test: testing" -fr -ss -system-chrome -http-proxy http://127.0.0.1:8080
3. Check both of the requests and observe that the second request does not include the specified header.

### Anything else:
Request 1 - Includes the "test" header.
<img width="945" alt="image" src="https://github.com/projectdiscovery/httpx/assets/3001014/476ef39c-9333-4c2d-b59f-62285a405161">

Request 2 - Does not include the "test" header.
<img width="1024" alt="image" src="https://github.com/projectdiscovery/httpx/assets/3001014/69522cb2-0784-413d-ac3b-e9c06afce773">

**Comment by jimen0** [comment] 2023-07-02 11:31
This is most likely caused due to the way httpx uses `go-rod/rod` for it.

https://github.com/projectdiscovery/httpx/blob/main/runner/headless.go#L93-L123

```go
func (b *Browser) ScreenshotWithBody(url string, timeout time.Duration) ([]byte, string, error) {
	page, err := b.engine.Page(proto.TargetCreateTarget{})
	if err != nil {
		return nil, "", err
	}
	page = page.Timeout(timeout)
	defer page.Close()

	if err := page.Navigate(url); err != nil {
		return nil, "", err
	}

	page.Timeout(2 * time.Second).WaitNavigation(proto.PageLifecycleEventNameFirstMeaningfulPaint)()

	if err := page.WaitLoad(); err != nil {
		return nil, "", err
	}
	_ = page.WaitIdle(1 * time.Second)

	screenshot, err := page.Screenshot(true, &proto.PageCaptureScreenshot{})
	if err != nil {
		return nil, "", err
	}

	body, err := page.HTML()
	if err != nil {
		return screenshot, "", err
	}

	return screenshot, body, nil
}
```

`go-rod` supports custom headers so it should be doable to support this. See https://pkg.go.dev/github.com/go-rod/rod#Page.SetExtraHeaders.

`(b *Browser) ScreenshotWithBody` should be updated to be configuration-aware and set the custom headers after creating the `page` object on https://github.com/projectdiscovery/httpx/blob/main/runner/headless.go#L94.

cc @ehsandeep

**Comment by ehsandeep** [comment] 2023-07-02 11:39
@xYantix @jimen0 This is because, `-ss` option makes the additional headless request for screenshots, **http probing** is still based on the standard http request, which can be improved in the future when headless probing becomes a thing.

so this is expected for now, `-ss` makes the additional headless request, let me know if you still have any questions on this.

**Comment by Mzack9999** [comment] 2023-12-27 20:44
Follow up ticket at https://github.com/projectdiscovery/httpx/issues/1265 - Closing the current issue as it's expected behavior

**Closed by Mzack9999** 2023-12-27 20:44 UTC
Labels: Type: Question
