### ISSUE TITLE
Could not write response

### ISSUE THREAD

**Issue by kurohost** [projectdiscovery/httpx#93] opened 2020-09-03 19:07 UTC
Hi, when using the `-sr` flag to save the response, it often tells me this because of too long file names as the files are called by the URLs:
`Could not write response, at path 'output/target.com_tooloooooooongpath?loonparams=true`
As a result you should try to solve this by saving the responses with shorter names.
Thanks for your amazing tools,
kurohost

**Comment by intrd** [comment] 2020-09-03 21:20
Same here: [https://github.com/projectdiscovery/httpx/issues/91#issue-690722880](#issue-690722880)

**Comment by intrd** [comment] 2020-09-03 23:58
Dirty/temporary little fix: #issuecomment-686822536

**Comment by bauthard** [comment] 2020-09-06 08:35
@kurohost this is a duplicate of https://github.com/projectdiscovery/httpx/issues/91

**Closed by bauthard** 2020-09-06 08:35 UTC
Labels: Type: Bug, Type: Enhancement
