### ISSUE TITLE
Add support to store http and https response separately

### ISSUE THREAD

**Issue by dark-warlord14** [projectdiscovery/httpx#21] opened 2020-06-15 15:09 UTC
Thanks for the awesome tool.

Its better if you add support to store http and https responses separately because right now they overwrite each other. I hope the below image will help to understand this

![image](https://user-images.githubusercontent.com/25666147/84673974-ff5c4f80-af47-11ea-9cd2-6bbe38df54e0.png)
 
Regards,

**Comment by bauthard** [comment] 2020-06-15 16:42
Hi @dark-warlord14, 

If you notice the output of `httpx`, they are same host, regardless of the input, the response file is generated based on the output of `httpx` which is the same host in this example, so this is expected behavior, if you have more example to share surly we can look into this, but as of not this working as intended. 

```
root@b0x:~/test# cat test.txt 
http://google.com
https://google.com

root@b0x:~/test# cat test.txt | httpx -silent 
https://google.com
https://google.com
```

**Comment by bauthard** [comment] 2020-06-22 07:49
Closing as this is working in the expected manner.

**Closed by bauthard** 2020-06-22 07:49 UTC
