### ISSUE TITLE
add -hl flag like katana for headless browser use without taking screenshots.

### ISSUE THREAD

**Issue by gprime31** [projectdiscovery/httpx#1258] opened 2023-06-26 16:52 UTC
add -hl flag like katana for headless browser use without taking screenshots.
thanks.
Prime31

**Comment by ehsandeep** [comment] 2024-05-28 09:21
this is duplicate of https://github.com/projectdiscovery/httpx/issues/1265

**Closed by ehsandeep** 2024-05-28 09:21 UTC
Labels: Type: Enhancement
