### ISSUE TITLE
Installation issue with go modules

### ISSUE THREAD

**Issue by amiralkizaru** [projectdiscovery/httpx#57] opened 2020-08-01 18:50 UTC
### Hello Team ###
Thank you very much for making this tool for us it's been very helpful for us
as I was poking around some features and flag I noticed that there is an issue with the `mc` flag it actually renders an error when you try to match a 200 or 302 status code 

## Test 

Let's say I want to check the js file that att.com has in the archive I came with this oneliner
`echo "att.com" | ~/go/bin/gau | grep '\.js$' | httpx -mc 200`

## Expected behavior 

Checking results that has 200 status code and display

## Issue
![issue](https://user-images.githubusercontent.com/32225186/89108293-1fc86680-d42f-11ea-8f59-ab4e638f29d7.png)

## What I tried

I tried to copy paste the same command you are using in the example section 
 `httpx -status-code -mc 200,302`

Ended up with the same message
![issue2](https://user-images.githubusercontent.com/32225186/89108349-9b2a1800-d42f-11ea-9891-aa5bc9f7ad71.png)

## Config
Ubuntu 18.04
Golang1.14
GO111MODULE=on
httpx version 0.0.7

**Comment by bauthard** [comment] 2020-08-01 20:01
Hey @amiralkizaru, 

Thank you for the feedback, as per your screenshot, looks like you are not on the latest version, to confirm this you can run `httpx -version`? it's working well on my side, FYI to use matcher/filter, you need to use `-status-code` flag as well.

**Comment by amiralkizaru** [comment] 2020-08-01 22:32
Hey @bauthard

Thank's for coming back at me fast
Looks like the issue was in the 0.0.7 version the 0.0.8 works fine

Have a good one

**Comment by KathanP19** [comment] 2020-08-04 03:49
`httpx -version`

```    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   / 
 / / / / /_/ /_/ /_/ /   |  
/_/ /_/\__/\__/ .___/_/|_|  
             /_/            

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 1.0.2
```
I am facing the same issue 

`cat probed_npg.txt | httpx -silent -follow-redirects -status-code -mc 200`

```
flag provided but not defined: -mc
Usage of httpx:
  -H value
        Custom Header
  -content-length
        Content Length
  -follow-host-redirects
        Only follow redirects on the same host
  -follow-redirects
        Follow Redirects
  -http-proxy string
        Http Proxy
  -json
        JSON Output
  -l string
        File containing domains
  -no-color
        No Color
  -o string
        File to write output to (optional)
  -ports value
        ports range (nmap syntax: eg 1,2-10,11)
  -response-in-json
        Server response directly in the tool output (-json only)
  -retries int
        Number of retries
  -silent
        Silent mode
  -status-code
        Extracts Status Code
  -store-response
        Store Response as domain.txt
  -store-response-dir string
        Store Response Directory (default current directory) (default ".")
  -threads int
        Number of threads (default 50)
  -timeout int
        Timeout in seconds (default 5)
  -title
        Extracts title
  -verbose
        Verbose Mode
  -version
        Show version of httpx
  -vhost
        Check for VHOSTs
  -web-server
        Prints out the Server header content
  -x string
        Request Method (default "GET")

```

**Comment by bauthard** [comment] 2020-08-04 08:06
Hey @KathanP19, 

For now, this should do the trick, we will investigate about the above issue. 

```
git clone github.com/projectdiscovery/httpx httpx-new; cd httpx-new/cmd/httpx; go build .; mv httpx /usr/local/bin/; httpx -h
```

**Comment by Haones** [comment] 2020-08-04 14:01
Had the same issue by installing with `GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx`, so had to install by building from source as well.

**Comment by bauthard** [comment] 2020-08-04 18:50
Should be fixed with https://github.com/projectdiscovery/httpx/pull/59 @Haones @KathanP19

**Closed by bauthard** 2020-08-04 18:50 UTC
Labels: Priority: High, Type: Bug

**Comment by Haones** [comment] 2020-08-05 16:18
Hi @bauthard,

Downloaded with `GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx` on fresh Ubuntu with fresh Go, it downloads **1.0.2** version (why there's **1** in major version while it supposed to be **0**) while the latest in releases is **0.0.8**. Is it intended behavior / version? Yet had to download source and build with go again to get **0.0.8** which is true latest version. 

Also had this conversation recently:
![](https://i.imgur.com/7hqajBs.png)

In this case there was even an error, but I had no errors with this "old" version **1.0.2**.

Thank you.

**Comment by nirvana-msu** [comment] 2020-08-08 19:41
This seems to be broken still - using `go get` command from readme somehow installs an old version, which reports `1.0.2` as its version.
```bash
GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx
```

```bash
~/go/bin$ ./httpx --version

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 1.0.2
```

**Comment by bauthard** [comment] 2020-08-08 19:43
Hi @nirvana-msu, 

We suggest using binary or using the GitHub installation method for the time being while we are looking into this again.

**Comment by nirvana-msu** [comment] 2020-08-08 19:44
Yeah using `git clone` and `go build` works fine indeed.

Thanks for the tool!
