### ISSUE TITLE
httpx always stuck at the end 

### ISSUE THREAD

**Issue by FuckAllWorld** [projectdiscovery/httpx#213] opened 2021-03-11 15:42 UTC
httpx always stuck at the end 

I always encounter situations like this... :-(

version v1.0.3

**Comment by ehsandeep** [comment] 2021-03-11 18:26
@FuckAllWorld do you have a list or something you can share to replicate this on the discord server?

**Comment by FuckAllWorld** [comment] 2021-03-12 01:22
i send mail for you , email address ?

**Comment by FuckAllWorld** [comment] 2021-03-12 01:23
@ehsandeep i send mail for you , email address ?

**Comment by ehsandeep** [comment] 2021-03-12 07:47
Sure, please send an email with the list to `contact@projectdiscovery.io`

**Comment by FuckAllWorld** [comment] 2021-03-12 09:53
@ehsandeep done. wait for your reply

**Comment by ehsandeep** [comment] 2021-03-12 14:34
Replied to the email, manage to complete the scan on the shared input list, as this is not a bug with httpx, closing this issue now.

**Closed by ehsandeep** 2021-03-12 14:34 UTC
