### ISSUE TITLE
-fs command not working

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/httpx#1813] opened 2024-07-09 16:06 UTC
filter string not working

![image](https://github.com/projectdiscovery/httpx/assets/42475284/8f13bd00-e29a-4bda-beb0-46ecb812dc25)

**Comment by dogancanbakir** [comment] 2024-07-09 18:36
duplicate of https://github.com/projectdiscovery/httpx/issues/1804

**Closed as not planned by dogancanbakir** 2024-07-09 18:36 UTC
Labels: duplicate, Type: Bug
