### ISSUE TITLE
Some 200 response urls returns 404 response in httpx

### ISSUE THREAD

**Issue by Silentsoul04** [projectdiscovery/httpx#732] opened 2022-08-23 08:57 UTC
### httpx version:
Tested version: v1.2.3, v1.2.0

### Current Behavior:
Some urls return 404 http response for valid 200 response urls. Was able to reproduce this on twitter site.

### Expected Behavior:
It should return 200 response.

### Steps To Reproduce:

```
echo "https://twitter.com/twitter" | httpx -fr -sc 

Response:
https://twitter.com/twitter [302,404]  [https://mobile.twitter.com/twitter]
```

Same command with redirected url return same response

```
echo https://mobile.twitter.com/twitter | httpx -fr -sc

https://mobile.twitter.com/twitter [404]

--------

echo "https://twitter.com/twitter" | httpx -fr -sc -x HEAD 

https://twitter.com/twitter [302,404] [HEAD] [https://mobile.twitter.com/twitter]

--------

echo https://mobile.twitter.com/twitter | httpx -fr -sc -http2

https://mobile.twitter.com/twitter [404] [http2]

```

Curl returns 200 status code for this url

```
curl -ik "https://mobile.twitter.com/twitter" -X HEAD

HTTP/2 200
```

**Comment by Silentsoul04** [comment] 2022-08-23 09:10
It seems it is golang url normalization issue. I was able to solve this by using `-unsafe`

```
echo "https://twitter.com/twitter" | httpx -fr -sc -unsafe

https://twitter.com/Twitter [200]
```

I also noticed using -unsafe flag sometimes don't return any response.

**Comment by jimen0** [comment] 2022-08-24 09:28
Unfortunately the problem here seems to be Twitter's server. It isn't very reliable. Notice how the same request sometimes results in a 200 OK while other times it gets a 404 Not Found.

```console
:~/research/projectdiscovery/httpx ‹dev›$ git reset --hard HEAD
HEAD is now at 2654ffa chore(deps): bump github.com/projectdiscovery/wappalyzergo from 0.0.55 to 0.0.56 (#731)
:~/research/projectdiscovery/httpx ‹dev›$ go build ./cmd/httpx
:~/research/projectdiscovery/httpx ‹dev›$ repeat 10 { echo "https://mobile.twitter.com/twitter" | ./httpx -fr -sc -silent -unsafe }
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
:~/research/projectdiscovery/httpx ‹dev›$ repeat 10 { echo "https://mobile.twitter.com/twitter" | ./httpx -fr -sc -silent }        
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
```

**Comment by Silentsoul04** [comment] 2022-08-24 15:27
I also faced similar behaviour with some other websites and subdomains. I think most people don't use --unsafe flag for probing subdomains and urls. without using -unsafe flag results are less reliable.


### without -unsafe 

```
for i in {1..10}; do echo "https://mobile.twitter.com/twitter" | httpx -fr -sc -silent; done

https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
https://mobile.twitter.com/twitter [404]
```

### with -unsafe 

```
~ $ for i in {1..10}; do echo "https://mobile.twitter.com/twitter" | httpx -fr -sc -silent -unsafe; done
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [400]
https://mobile.twitter.com/twitter [200]
https://mobile.twitter.com/twitter [400]
```

if it is server issue, Wonder if it is fixable behaviour or not for httpx 🤔

**Comment by jimen0** [comment] 2022-08-25 07:10
> if it is server issue, Wonder if it is fixable behaviour or not for httpx 🤔

httpx can't fix server issues. If a server returns an HTTP status code, there's nothing httpx can do to change it.

Unless you have a generic reproducer that shows this happens too with a server we can control and which always returns a 302 -> 200 chain for example, this seems like a false positive issue to me.

**Comment by Silentsoul04** [comment] 2022-08-25 12:45
> this seems like a false positive issue to me.

Nope. I don't think so.

The `curl` command works perfectly fine.

```
for i in {1..10}; do curl -I https://mobile.twitter.com/twitter 2>/dev/null | head -n 1 | cut -d$' ' -f2; done

200
200
200
200
200
200
200
200
200
200
```

If it is server issue, then why this issue is only happening with httpx without using -unsafe flag ?

**Comment by jimen0** [comment] 2022-08-25 13:31
> If it is server issue, then why this issue is only happening with httpx without using -unsafe flag ?

Because of the differences between the HTTP request your curl command sends and what httpx sends when using the unsafe method. Can you reproduce the 200 OK responses by sending exactly the same HTTP request with both? (a pcap or wireshark screenshots would be great if you can).

If not, then, again, this isn't httpx can fix since the response comes from the server.

**Comment by jimen0** [comment] 2022-08-25 13:47
Use the `debug-req` flag of httpx or Wireshark and you'll be able to see the traffic.

```
DEBUG:
   -health-check, -hc        run diagnostic check up
   -debug                    display request/response content in cli
   -debug-req                display request content in cli
   -debug-resp               display response content in cli
```

**Comment by sullo** [comment] 2022-08-25 15:00
`curl -v` will also show you the request curl makes. And `https://curl.se/h2c/` looks like it can convert httpx request to a curl command so you can test that direction too. In scenarios like this I also find it helpful to put them into something like Burp repeater and tinker with the difference to figure out what causes an issue. 

The inconsistency _may_ even be interesting from a security perspective.

**Comment by Mzack9999** [comment] 2022-09-23 12:22
It seems like the server behaves differently depending on the random user agent. For example:
- `User-Agent: Opera/9.80 (X11; Linux i686) Presto/2.12.388 Version/12.16` => `HTTP/1.1 200 OK`
- `User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.4 (KHTML like Gecko) Chrome/22.0.1229.79 Safari/537.4` => `HTTP/1.1 302 Found` => `HTTP/1.1 400 Bad Request`

A more thoughtful selection of user agent categories should reduce the number of unexpected server behaviors. This should be fixed with https://github.com/projectdiscovery/useragent (WIP)

**Closed** 2023-01-06 13:46 UTC
Labels: Priority: Medium, Status: Completed, Type: Bug, Investigation
